try:
    print("x")
except:
    print("Somethings else went wrong")
else:
    print("Nothing went wrong")

finally:
    print("the 'try except is finished")
